---
- hosts: appserver
  become: yes
  tasks: 
    - name: ping ll
      ping:

    - name: installing  tomcat
      yum: 
        name: tomcat
        state: present
    - name: check the war file existances
      stat:
        path: "{{destnationdir}}{{destnationwar}}"
      register: warst
    - name: warst dispaly name od package of instalation	
      debug:
        msg: "{{warst}}"
    - name: delete the war file
      file: 
        path: "{{destnationdir}}{{destnationwar}}"
        state: absent
      register: wardel
    - name: wardel dispaly name od package of instalation	
      debug:
        msg: "{{wardel}}"
      when: warst.stat.exists==true
    - name:  copying the war file into webapp folder
      copy:
        src: "{{sourcedir}}{{sourcewar}}"
        dest: "{{destnationdir}}{{destnationwar}}"
      notify:
      - restartingtomcat
      when: wardel.state=="absent"
 
      
           
  handlers: 
    - name: restartingtomcat
      service:
        name: tomcat
        state: restarted 
        